# Writes machine/environment specs used by the paper text:
#   data/machine.txt   raw versioninfo dump
#   generated/machine.tex   TeX macros (\CPUmodel, \NumThreads, ...)
# Included by generate_all.jl (after common.jl).

using InteractiveUtils

tex_escape(s::AbstractString) = replace(s, "_" => "\\_", "&" => "\\&", "%" => "\\%", "#" => "\\#")

function write_machine_info()
    cpu = strip(Sys.cpu_info()[1].model)
    nthreads = Threads.nthreads()
    ram_gb = round(Sys.total_memory() / 2^30; digits = 0)
    julia_ver = string(VERSION)
    commit = try
        strip(read(`git -C $REPO_DIR rev-parse --short HEAD`, String))
    catch
        "unknown"
    end

    open(joinpath(DATA_DIR, "machine.txt"), "w") do io
        println(io, "generated: ", Dates.now())
        println(io, "package commit: ", commit)
        println(io, "Threads.nthreads() = ", nthreads)
        versioninfo(io; verbose = false)
    end

    open(joinpath(GEN_DIR, "machine.tex"), "w") do io
        println(io, "% auto-generated by paper/scripts/machine_info.jl")
        println(io, "\\newcommand{\\CPUmodel}{", tex_escape(cpu), "}")
        println(io, "\\newcommand{\\RAMgb}{", Int(ram_gb), "}")
        println(io, "\\newcommand{\\NumThreads}{", nthreads, "}")
        println(io, "\\newcommand{\\JuliaVersion}{", julia_ver, "}")
        println(io, "\\newcommand{\\PkgCommit}{", tex_escape(commit), "}")
    end
    @info "machine info written" cpu nthreads ram_gb julia_ver commit
end

write_machine_info()
