# Study s13: the discrete phase-unwrapping march versus the integration back-ends,
# all measured on the SAME machine (so the factors are machine-independent),
# plus the GPU and number-format tables measured with NyquistGPU (gpu/).
#
# Produces: data/unwrap_grid.csv, data/unwrap_boundary.csv, data/gpu_final.csv,
#           data/precision_scaled.csv, tables/tab_unwrap.tex, tables/tab_unwrap_stress.tex,
#           tables/tab_gpu.tex, tables/tab_precision.tex, generated/unwrap_numbers.tex
#
# Run (light environment, no plotting packages needed):
#   julia --project=gpu/validate -t auto paper/scripts/studies/s13_unwrap.jl

using InterpolatedNyquist, Statistics, Printf, Dates
const REPO = normpath(joinpath(@__DIR__, "..", "..", ".."))
const PAPER = joinpath(REPO, "paper")
include(joinpath(REPO, "gpu", "scripts", "systems.jl"))
const N = 100
cpu = strip(Sys.cpu_info()[1].model)
nthr = Threads.nthreads()

fmt_t(t) = t < 1 ? @sprintf("%.1f\\,ms", 1e3t) : @sprintf("%.2f\\,s", t)
best(f; reps = 3) = (f(); minimum(@elapsed(f()) for _ in 1:reps))

# --------------------------------------------------------------------------
# 1. chart timings, 100x100, all back-ends, same machine
# --------------------------------------------------------------------------
rows = Any[]
for name in ("fourth", "showcase", "turning")
    sys = SYSTEMS[name]
    pts = vec([(x, y) for x in range(sys.xr...; length = N), y in range(sys.yr...; length = N)])
    Dref = sys.ref
    Dun = (λ, p) -> sys.D(λ, p, sys.c)                      # entire form (turning: denominators cleared)
    kwr = (n_power_max = sys.ref_npow, ω_max = 1e4)
    Zref, = calculate_unstable_roots_p_vec(Dref, pts; n_roots_to_track = 0, reltol = 1e-8,
        abstol = 1e-8, kwr...)
    wrong(Z) = count(Z .!= Zref)
    t = best(() -> calculate_unstable_roots_p_vec(Dref, pts; kwr...); reps = name == "turning" ? 1 : 3)
    Z, = calculate_unstable_roots_p_vec(Dref, pts; kwr...)
    push!(rows, (name, "ODE Vern9 + root (default)", t, wrong(Z), ""))
    t = best(() -> calculate_unstable_roots_quadgk_p_vec(Dref, pts; kwr...); reps = name == "turning" ? 1 : 3)
    Z, = calculate_unstable_roots_quadgk_p_vec(Dref, pts; kwr...)
    push!(rows, (name, "QuadGK, Z only", t, wrong(Z), ""))
    t = best(() -> calculate_unstable_roots_fixed_step_p_vec(Dref, pts; steps = 500, kwr...))
    Z, = calculate_unstable_roots_fixed_step_p_vec(Dref, pts; steps = 500, kwr...)
    push!(rows, (name, "fixed-step (500)", t, wrong(Z), ""))
    kwu = (n_power_max = sys.npow, sys.kw...)
    t = best(() -> calculate_unstable_roots_unwrap_p_vec(Dun, pts; kwu...))
    Z, = calculate_unstable_roots_unwrap_p_vec(Dun, pts; kwu...)
    ev = [InterpolatedNyquist._unwrap_march(InterpolatedNyquist.NyquistWrapper{typeof(pts[1])}(Dun),
        p, 0.0, 1; ω_max = 1e5, sys.kw...)[3] for p in pts]
    push!(rows, (name, "unwrap + root (new)", t, wrong(Z), string(round(Int, median(ev)))))
    @printf("%-9s done\n", name)
end
const TITLES = Dict("fourth" => "4th-order + delay", "showcase" => "2-DOF DAE showcase",
                    "turning" => "two-mode turning")
open(joinpath(PAPER, "data", "unwrap_grid.csv"), "w") do io
    println(io, "system,backend,chart_time_s,per_point_us,wrong_Z,evals_median")
    for r in rows
        println(io, join((r[1], r[2], r[3], 1e6 * r[3] / N^2, r[4], r[5]), ','))
    end
end
open(joinpath(PAPER, "tables", "tab_unwrap.tex"), "w") do io
    println(io, "% auto-generated by paper/scripts/studies/s13_unwrap.jl -- do not edit by hand")
    println(io, "\\begin{tabular}{llrrrr}\n\\toprule")
    println(io, "system & back-end & chart (100\$\\times\$100) & per point [\$\\mu\$s] & wrong \$Z\$ & speed-up \\\\\n\\midrule")
    for name in ("fourth", "showcase", "turning")
        sub = filter(r -> r[1] == name, rows)
        tode = sub[1][3]
        for r in sub
            @printf(io, "%s & %s & %s & %.1f & %d & %s \\\\\n", TITLES[name], r[2], fmt_t(r[3]),
                1e6 * r[3] / N^2, r[4], r[2] == "unwrap + root (new)" ? @sprintf("\\textbf{%.0f\$\\times\$}", tode / r[3]) : @sprintf("%.1f\$\\times\$", tode / r[3]))
        end
        name != "turning" && println(io, "\\midrule")
    end
    println(io, "\\bottomrule\n\\end{tabular}")
end

# --------------------------------------------------------------------------
# 2. near-boundary stress (showcase Hopf boundary, both sides)
# --------------------------------------------------------------------------
sys = SYSTEMS["showcase"]
Dsc = sys.ref
σ_of(P) = calculate_unstable_roots_direct(Dsc, (P, 1.5); ω_max = 1e4, reltol = 1e-10, abstol = 1e-10,
    n_power_max = 4, refinement_method = :Newton, refinement_steps = 15)[4]
PB = let lo = 2.0, hi = 3.0
    for _ in 1:60
        m = (lo + hi) / 2
        σ_of(m) < 0 ? (lo = m) : (hi = m)
    end
    (lo + hi) / 2
end
stress = Any[]
for s in (-1, 1), d in (1e-2, 1e-4, 1e-6, 1e-8, 1e-10, 1e-12)
    p = (PB + s * d, 1.5)
    zo = calculate_unstable_roots_direct(Dsc, p; ω_max = 1e4, reltol = 1e-8, abstol = 1e-8, n_power_max = 4)[1]
    zu = calculate_unstable_roots_unwrap(Dsc, p; n_power_max = 4)[1]
    ev = InterpolatedNyquist._unwrap_march(InterpolatedNyquist.NyquistWrapper{typeof(p)}(Dsc), p, 0.0, 1)[3]
    push!(stress, (s * d, s < 0 ? 2 : 4, zo, zu, ev))
end
open(joinpath(PAPER, "data", "unwrap_boundary.csv"), "w") do io
    println(io, "dP,Z_true,Z_ode_1e-8,Z_unwrap,evals_unwrap")
    foreach(r -> println(io, join(r, ',')), stress)
end
open(joinpath(PAPER, "tables", "tab_unwrap_stress.tex"), "w") do io
    println(io, "% auto-generated by paper/scripts/studies/s13_unwrap.jl -- do not edit by hand")
    println(io, "\\begin{tabular}{rcccr}\n\\toprule")
    println(io, "\$P-P_b\$ & true \$Z\$ & ODE Vern9 (\$10^{-8}\$) & unwrap & evaluations \\\\\n\\midrule")
    for r in stress
        mark(z) = z == r[2] ? string(z) : "\\textbf{$(z)}"
        @printf(io, "\$%s\$ & %d & %s & %s & %d \\\\\n", replace(@sprintf("%+.0e", r[1]), "e-0" => "\\cdot10^{-", "e-" => "\\cdot10^{-") * "}",
            r[2], mark(r[3]), mark(r[4]), r[5])
    end
    println(io, "\\bottomrule\n\\end{tabular}")
end

# --------------------------------------------------------------------------
# 3. GPU and number-format tables: s14_gpu_tables.jl (also runnable on its own)
# --------------------------------------------------------------------------
include(joinpath(@__DIR__, "s14_gpu_tables.jl"))

# --------------------------------------------------------------------------
# 4. macros
# --------------------------------------------------------------------------
sp(name) = (sub = filter(r -> r[1] == name, rows); sub[1][3] / sub[4][3])
ppu(name) = 1e6 * filter(r -> r[1] == name, rows)[4][3] / N^2
open(joinpath(PAPER, "generated", "unwrap_numbers.tex"), "w") do io
    println(io, "% auto-generated by paper/scripts/studies/s13_unwrap.jl")
    println(io, "\\newcommand{\\UwCPU}{$(cpu)}")
    println(io, "\\newcommand{\\UwThreads}{$(nthr)}")
    @printf(io, "\\newcommand{\\UwSpeedFourth}{%.0f}\n", sp("fourth"))
    @printf(io, "\\newcommand{\\UwSpeedShowcase}{%.0f}\n", sp("showcase"))
    @printf(io, "\\newcommand{\\UwSpeedTurning}{%.0f}\n", sp("turning"))
    @printf(io, "\\newcommand{\\UwUsFourth}{%.1f}\n", ppu("fourth"))
    @printf(io, "\\newcommand{\\UwUsShowcase}{%.1f}\n", ppu("showcase"))
    @printf(io, "\\newcommand{\\UwUsTurning}{%.1f}\n", ppu("turning"))
end
println("s13 done: ", cpu, " x", nthr)
