# Study s14: GPU and number-format tables. The measurements themselves are made with
# NyquistGPU on Colab (gpu/scripts/gpu_final.jl, gpu/scripts/precision_scaled.jl);
# this script only turns the collected CSV files into paper tables.
#
# Produces: data/gpu_final.csv, data/precision_scaled.csv, tables/tab_gpu.tex,
#           tables/tab_precision.tex, generated/gpu_numbers.tex
#
# Run on its own (no packages needed) or included by s13_unwrap.jl:
#   julia paper/scripts/studies/s14_gpu_tables.jl

using Printf
if !@isdefined(REPO)
    const REPO = normpath(joinpath(@__DIR__, "..", "..", ".."))
    const PAPER = joinpath(REPO, "paper")
end

gsrc = joinpath(REPO, "gpu", "results", "gpu_final_summary.csv")
if isfile(gsrc)
    cp(gsrc, joinpath(PAPER, "data", "gpu_final.csv"); force = true)
    recs = [split(l, ',') for l in readlines(gsrc)[2:end] if !isempty(strip(l))]
    order(g) = occursin("T4", g) ? 1 : occursin("L4", g) ? 2 : occursin("A100", g) ? 3 : 4
    gpus = sort(unique(first.(recs)); by = order)
    short(g) = occursin("RTX PRO 6000", g) ? "RTX PRO 6000 (Blackwell)" :
               occursin("A100", g) ? "A100 (40\\,GB)" : replace(g, "Tesla " => "", "NVIDIA " => "")
    val(g, c, k = 3) = (r = findfirst(r -> r[1] == g && r[2] == c, recs); r === nothing ? "--" : recs[r][k])
    # the same cases at 8K (7680x4320), where measured
    g8 = joinpath(REPO, "gpu", "results", "gpu_final_8k_summary.csv")
    recs8 = isfile(g8) ? [split(l, ',') for l in readlines(g8)[2:end] if !isempty(strip(l))] : Any[]
    isfile(g8) && cp(g8, joinpath(PAPER, "data", "gpu_final_8k.csv"); force = true)
    val8(g, c, k = 3) = (r = findfirst(r -> r[1] == g && r[2] == c, recs8); r === nothing ? "--" : recs8[r][k])
    # milliseconds to three significant figures (at least two decimals below 10 ms)
    ms(v) = v == "--" ? v : (x = parse(Float64, v); x >= 100 ? @sprintf("%.0f", x) : x >= 10 ? @sprintf("%.1f", x) : x >= 1 ? @sprintf("%.2f", x) : @sprintf("%.3f", x))
    open(joinpath(PAPER, "tables", "tab_gpu.tex"), "w") do io
        println(io, "% auto-generated by paper/scripts/studies/s14_gpu_tables.jl -- do not edit by hand")
        println(io, "\\begin{tabular}{lrrrrrr}\n\\toprule")
        println(io, " & \\multicolumn{3}{c}{full HD, \$\\wmax=10^{5}\$} & \\multicolumn{2}{c}{full HD, \$\\wmax=15\$} & 8K \\\\")
        println(io, "\\cmidrule(lr){2-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-7}")
        println(io, "GPU & Float64 & Float32 & [Mpts/s] & Float32 & Float16 & Float32 \\\\\n\\midrule")
        for g in gpus
            @printf(io, "%s & %s & \\textbf{%s} & %s & %s & %s & %s \\\\\n", short(g),
                ms(val(g, "Float64 wmax=1e5 (reference)")), ms(val(g, "Float32 wmax=1e5")),
                round(Int, parse(Float64, val(g, "Float32 wmax=1e5", 5))),
                ms(val(g, "Float32 wmax=15")), ms(val(g, "Float16 wmax=15 scaled")), ms(val8(g, "Float32 wmax=1e5")))
        end
        println(io, "\\bottomrule\n\\end{tabular}")
    end
    best = gpus[end]
    open(joinpath(PAPER, "generated", "gpu_numbers.tex"), "w") do io
        println(io, "% auto-generated by paper/scripts/studies/s14_gpu_tables.jl")
        println(io, "\\newcommand{\\GpuBest}{$(short(best))}")
        println(io, "\\newcommand{\\GpuBestFsixtyfour}{$(ms(val(best, "Float64 wmax=1e5 (reference)")))}")
        println(io, "\\newcommand{\\GpuBestFthirtytwo}{$(ms(val(best, "Float32 wmax=1e5")))}")
        println(io, "\\newcommand{\\GpuBestFsixteen}{$(ms(val(best, "Float16 wmax=15 scaled")))}")
        println(io, "\\newcommand{\\GpuBestFthirtytwoFifteen}{$(ms(val(best, "Float32 wmax=15")))}")
        println(io, "\\newcommand{\\GpuBestSlider}{$(ms(val(best, "slider loop Float32 wmax=1e5")))}")
        println(io, "\\newcommand{\\GpuFsixteenWrong}{$(@sprintf("%.3g", parse(Float64, val(best, "Float16 wmax=15 scaled", 7))))}")
        println(io, "\\newcommand{\\GpuFsixteenFlagged}{$(@sprintf("%.3g", parse(Float64, val(best, "Float16 wmax=15 scaled", 8))))}")
        println(io, "\\newcommand{\\GpuEightKFthirtytwo}{$(ms(val8(best, "Float32 wmax=1e5")))}")
        println(io, "\\newcommand{\\GpuEightKFsixteen}{$(ms(val8(best, "Float16 wmax=15 scaled")))}")
        println(io, "\\newcommand{\\GpuEightKSlider}{$(ms(val8(best, "slider loop Float32 wmax=1e5")))}")
    end
end

psrc = joinpath(REPO, "gpu", "results", "maps", "precision_scaled_400x400.csv")
isfile(psrc) && cp(psrc, joinpath(PAPER, "data", "precision_scaled.csv"); force = true)
pcsv = joinpath(PAPER, "data", "precision_scaled.csv")
if isfile(pcsv)
    recs = [split(l, ',') for l in readlines(pcsv)[2:end] if !isempty(strip(l))]
    open(joinpath(PAPER, "tables", "tab_precision.tex"), "w") do io
        println(io, "% auto-generated by paper/scripts/studies/s14_gpu_tables.jl -- do not edit by hand")
        println(io, "\\begin{tabular}{llrrr}\n\\toprule")
        println(io, "format of \$\\Dfun\$ & bits (exp./mant.) & wrong \$Z\$ [\\%] & flagged [\\%] & failed [\\%] \\\\\n\\midrule")
        bits = Dict("Float64" => "11/52", "Float32" => "8/23", "Float16" => "5/10",
            "BFloat16 (emu)" => "8/7", "Float8 E5M2 (emu)" => "5/2", "Float8 E4M3 (emu)" => "4/3",
            "Float4 E2M1 (emu)" => "2/1")
        for f in ("Float64", "Float32", "Float16", "BFloat16 (emu)", "Float8 E5M2 (emu)",
                  "Float8 E4M3 (emu)", "Float4 E2M1 (emu)")
            cand = filter(r -> r[1] == f, recs)
            isempty(cand) && continue
            r = cand[argmin([parse(Float64, c[4]) for c in cand])]     # best scaling strategy
            @printf(io, "%s & %s & %.3f & %.2f & %.2f \\\\\n", replace(f, " (emu)" => "\$^\\ast\$"),
                bits[f], parse(Float64, r[4]), parse(Float64, r[6]), parse(Float64, r[7]))
        end
        println(io, "\\bottomrule\n\\end{tabular}")
    end
end
