"""Study s15: parallel scaling of the discrete march -- CPU threads and GPU threads.

Inputs (measured, see paper/data/parallel/README.md):
  data/parallel/thread_scaling_local.csv  CPU threads 1..12 (i5-10400), gpu/scripts/thread_scaling.jl
  data/parallel/thread_scaling_colab.csv  CPU threads 1..48 (Colab G4 host) and GPU full-chart times
  data/parallel/lane_scaling_<GPU>_<T>.csv GPU with exactly N threads, gpu/scripts/gpu_lane_scaling.jl
Produces:
  figures/fig_parallel_scaling.pdf, tables/tab_parallel.tex, generated/parallel_numbers.tex

Run:  python paper/scripts/studies/s15_parallel_scaling.py   (matplotlib only)
"""
import csv, glob, os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

PAPER = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
D = os.path.join(PAPER, "data", "parallel")
SYS = "fourth"                       # the example shown in the paper

# GPU facts (vendor specifications): CUDA cores and resident threads (SMs x max threads per SM)
GPUS = [  # key, label, colour, marker, cores, resident threads
    ("T4", "T4", "#e87ba4", "P", 2560, 40 * 1024),
    ("L4", "L4", "#c98500", "D", 7424, 58 * 1536),
    ("A100", "A100", "#1baf7a", "v", 6912, 108 * 2048),
    ("G4", "RTX PRO 6000", "#eb6834", "^", 24064, 188 * 1536),
]


def read(path):
    return list(csv.DictReader(open(path, encoding="utf-8")))


def cpu_series(tag):
    rows = [r for r in read(os.path.join(D, f"thread_scaling_{tag}.csv"))
            if r["device"] == "CPU" and r["system"] == SYS]
    return sorted((int(r["threads"]), float(r["ms"]) / (int(r["nx"]) * int(r["ny"])) * 1e6) for r in rows)


def gpu_series(key, T):
    f = os.path.join(D, f"lane_scaling_{key}_{'F64' if T == 'Float64' else 'F32'}.csv")
    if not os.path.exists(f):
        return []
    return sorted((int(r["threads"]), float(r["ms_per_Mpt"])) for r in read(f) if r["system"] == SYS)


plt.rcParams.update({"font.family": "serif", "font.size": 9, "axes.labelsize": 9, "legend.fontsize": 7.5,
                     "xtick.labelsize": 8, "ytick.labelsize": 8})
fig, ax = plt.subplots(figsize=(6.3, 4.0))
local_cpu, colab_cpu = cpu_series("local"), cpu_series("colab")
ax.plot(*zip(*local_cpu), "-o", color="#2a78d6", ms=4, lw=1.6, label="CPU, desktop (6 cores)")
ax.plot(*zip(*colab_cpu), "-s", color="#0d366b", ms=4, lw=1.6, label="CPU, server (48 threads)")
for key, lab, col, mk, cores, res in GPUS:
    s32, s64 = gpu_series(key, "Float32"), gpu_series(key, "Float64")
    if s32:
        ax.plot(*zip(*s32), "-", marker=mk, color=col, ms=4, lw=1.6, label=f"GPU {lab}, Float32")
    if s64:
        ax.plot(*zip(*s64), "--", marker=mk, color=col, ms=3, lw=1.0, alpha=0.6, label=f"GPU {lab}, Float64")
# ideal 1/n line through the single-thread CPU time
t1 = colab_cpu[0][1]
ax.plot([1, 1e4], [t1, t1 / 1e4], ":", color="#555555", lw=1.0, label="ideal: $1/n$")
# real-time levels: a frame of 8K (33.2 Mpt) or full HD (2.07 Mpt) at 30 frames per second
for npts, name in ((7680 * 4320, "8K"), (1920 * 1080, "full HD")):
    lvl = (1000 / 30) / (npts / 1e6)
    ax.axhline(lvl, color="#999999", lw=0.8)
    ax.text(1.3, lvl * 1.15, f"{name} at 30 frames/s", fontsize=7, color="#555555")
ax.set_xscale("log"); ax.set_yscale("log"); ax.set_ylim(0.2, 6e5)
ax.set_xlabel("number of threads $n$ (CPU threads / GPU threads)")
ax.set_ylabel("time for $10^6$ points [ms]  (1 s = 1 $\\mu$s per point)")
ax.grid(color="#e8e8e8", lw=0.6, which="major"); ax.set_axisbelow(True)
for s in ("top", "right"):
    ax.spines[s].set_visible(False)
ax.legend(frameon=False, ncol=2, loc="lower left")
fig.tight_layout()
fig.savefig(os.path.join(PAPER, "figures", "fig_parallel_scaling.pdf"))
fig.savefig(os.path.join(PAPER, "figures", "fig_parallel_scaling.png"), dpi=200)

# ---- table: single-thread cost, saturated cost, effective parallelism ----
def sat(series):
    return min(t for _, t in series)


rows = []
cpu1 = colab_cpu[0][1]
for tag, lab, s in (("local", "CPU desktop, i5-10400 (6 cores)", local_cpu), ("colab", "CPU server (G4 host, 48 threads)", colab_cpu)):
    rows.append((lab, "Float64", s[0][1] / 1e3, min(t for _, t in s), s[-1][0], s[0][1] / min(t for _, t in s), None))
out = {}
for key, lab, col, mk, cores, res in GPUS:
    for T in ("Float32", "Float64"):
        s = gpu_series(key, T)
        if not s:
            continue
        t1g, ts = s[0][1], sat(s)
        peff = t1g / ts
        rows.append((f"GPU {lab}", T, t1g / 1e3, ts, cores, peff, peff / cores))
        out[(key, T)] = (t1g, ts, peff, cores)

with open(os.path.join(PAPER, "tables", "tab_parallel.tex"), "w", encoding="utf-8") as io:
    io.write("% auto-generated by paper/scripts/studies/s15_parallel_scaling.py -- do not edit by hand\n")
    io.write("\\begin{tabular}{llrrrr}\n\\toprule\n")
    io.write(" & & one thread & saturated & effective & CUDA cores \\\\\n")
    io.write("hardware & format & [$\\mu$s/point] & [ns/point] & parallelism & (ratio) \\\\\n\\midrule\n")
    for lab, T, t1us, tsat, cores, peff, ratio in rows:
        if ratio is None:
            io.write(f"{lab} & {T} & {t1us:.2f} & {tsat:.0f} & {peff:.1f} & {cores} threads \\\\\n")
        else:
            io.write(f"{lab} & {T} & {t1us:.1f} & {tsat:.2f} & {peff:,.0f} & {cores} ({ratio:.2f}) \\\\\n".replace(",", "\\,"))
    io.write("\\bottomrule\n\\end{tabular}\n")

g = out[("G4", "Float32")]
a64 = out[("A100", "Float64")]
with open(os.path.join(PAPER, "generated", "parallel_numbers.tex"), "w", encoding="utf-8") as io:
    io.write("% auto-generated by paper/scripts/studies/s15_parallel_scaling.py\n")
    io.write(f"\\newcommand{{\\ParCpuOneUs}}{{{cpu1 / 1e3:.1f}}}\n")                       # µs per point, 1 CPU thread
    io.write(f"\\newcommand{{\\ParCpuFortyEightSpeedup}}{{{colab_cpu[0][1] / colab_cpu[-1][1]:.0f}}}\n")
    io.write(f"\\newcommand{{\\ParCpuSixteenSpeedup}}{{{colab_cpu[0][1] / dict(colab_cpu)[16]:.1f}}}\n")
    io.write(f"\\newcommand{{\\ParGpuOneUsLo}}{{{min(v[0] for k, v in out.items() if k[1] == 'Float32') / 1e3:.0f}}}\n")
    io.write(f"\\newcommand{{\\ParGpuOneUsHi}}{{{max(v[0] for k, v in out.items() if k[1] == 'Float32') / 1e3:.0f}}}\n")
    io.write(f"\\newcommand{{\\ParBestNsPerPoint}}{{{g[1]:.2f}}}\n")
    io.write(f"\\newcommand{{\\ParBestEightKms}}{{{g[1] * 7680 * 4320 / 1e6:.0f}}}\n")
    io.write(f"\\newcommand{{\\ParBestFullHDms}}{{{g[1] * 1920 * 1080 / 1e6:.1f}}}\n")
    io.write(f"\\newcommand{{\\ParBestPeff}}{{{g[2]:,.0f}}}\n".replace(",", "\\,"))
    io.write(f"\\newcommand{{\\ParBestVsCpu}}{{{cpu1 / g[1]:,.0f}}}\n".replace(",", "\\,"))
print("written fig_parallel_scaling.pdf, tab_parallel.tex, parallel_numbers.tex")
for r in rows:
    print(r)
